"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "./components/AppWalletProvider";
import { KindeProvider } from "@kinde-oss/kinde-auth-nextjs";
const inter = Inter({ subsets: ["latin"] });
import RecoilContextProvider from "@/app/lib/RecoilContextProvider"
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <RecoilContextProvider>
        <KindeProvider
          clientId="957577ab0f47417589a14eda33b0b44b"
          domain="https://theboys.kinde.com"
          logoutUri={window.location.origin}
          redirectUri={window.location.origin}
        >
          <AppWalletProvider>{children}</AppWalletProvider>
        </KindeProvider>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
